_name_: standalone
d_state: 64
channels: 1
bidirectional: false
activation: gelu
postact: null
dropout: ${..dropout} # Same as null
measure: legs
dt_min: 0.001
dt_max: 0.1
trainable: true
lr: 0.001
n_ssm: 1
l_max: ${oc.select:dataset.__l_max,null} # Grab dataset length if exists, otherwise set to 1 and kernel will automatically resize
verbose: true
